# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    tags:
      - 're*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'test2'
      - name: Create Release
        id: create_release
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release-notes-5'
  # test-branch:
  #   needs: build
  #   name: prueba
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #       with:
  #         ref: release-notes-2
  #     - name: Set up Python 3.9
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.8
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  #     - name: Run unit tests
  #       id: correr-test
  #       run: 
  #         python -m unittest discover tests
  #     - name: Run coverage
  #       id: correr-coverage
  #       run:  |
  #         coverage run -m unittest discover tests
  #         coverage report -m
  # merge-main:  
  #   needs: test-branch
  #   name: Merge master into release after a PR is merged
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v2
  #     - name: merge
  #       uses: mtanzi/action-automerge@v1
  #       id: merge
  #       with:
  #         github_token: ${{ github.token }}
  #         source: 'release-notes-3'
  #         target: 'main'